### ISSUE TITLE
What theme should we have for OpenConCam 2017

### ISSUE THREAD

**Issue by KirstieJane** [OpenConCam/OpenConCam#11]
Please comment below with any suggestions for our OpenConCam 2017 workshop.

Please use the [emoji reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) if there are posts you particularly agree with!

Summary of suggestions so far:

* Communication across different stakeholders within a university
  * Note, this doesn't have to be stakeholders specifically within Cambridge, we could invite people from institutions that have put in place initiatives we admire.
* Engaging with politicians to fight for researchers rights
  * Focus on empowering open advocates to effect change

**Comment by Bjwebb** [comment]
What about a focus on communication across different stakeholders in the university? Heads of department, early career researchers, admin teams etc.

**Comment by lgatto** [comment]
Sorry for not being very enthusiastic about this, but in my experience, the communication across the university, or those in power at the university, is not straightforward when it comes to open science. There's the ERCs and the OSC, and that's pretty much it in terms of genuine support of open science. That doesn't mean there is no support from some more senior academics, or the odd librarian, but in general, *the University* or the *the Library* does not engage in open science.

I wish I was wrong, though.

**Comment by corinalogan** [comment]
How to engage with politicians to lobby for researcher rights? Publishers are lobbying politicians so maybe we fight fire with fire. I'd love to hear from politicians about how their world works, how decisions really get made, and what we as researchers can do to influence this. For example, who do I talk to if I want Cambridge and the UK to stop using Jisc Collections and start negotiating better deals with publishers? And what can they do about this?

**Comment by lgatto** [comment]
> How to engage with politicians to lobby for researcher rights? 

I like that, Corina! May be we could have a talk/session on that topic, and invite senior academics, journalists and/or politicians that sympathise to our cause.

**Comment by KirstieJane** [comment]
@lgatto and @corinalogan - thank you for joining in!! I'm about to send an email around to let people know to come and join the conversation here and it's already going! 🙌 

I'd like to develop the idea that I typed under @Bjwebb's login earlier today (we were showing @martateperek how issues work!).

The idea was to discuss all the different stakeholders across the university, for example:

* An early career researcher
* A new PhD student
* A head of department
* An admin team member - discussing how to change beurocracy in department
* A member of the legal team (eg: Clinical School governance)

We'd be inviting people who HAVE shown a committment to changing behaviours and opening up the research in their domain. The conversations would focus on (for example): What has to happen to address change? What are the blockers? Who do we need to involve? What are their motivations etc.

I see both of your frustrations with the majority of people in both the University and many in the library...but maybe we don't need to only have speakers from Cambridge! What if we brought in folk from other institutions to show that it *can* be done?

Finally, I'm open to being wrong, but I'm nervous that we don't have the critical mass in Cambridge for a focus on lobbying for researcher rights. It seems to me like the two ideas are taking quite polar opposite tactics for change: playing nice and saying "I understand, what can we do to help?" vs "We are the future, change or be left behind!".

What do you think?

**Comment by martateperek** [comment]
@lgatto I totally see your point and I fully agree with you. The reason for proposing a topic like this is we thought it would be interesting to actually do sth about this disengagement. What actions would need to be taken / what would need to happen to engage those who are currently disengaged (the majority)? 

We've organised a Birds of Feathers discussion at a conference I've been to about engaging the senior people - lots of useful tips - see the draft blog post: https://docs.google.com/document/d/1h1XwDmYvjgP_qcrI7USi8sWS1sdNZr_UfDba8XQqoE0/edit?usp=sharing 

Maybe we could invite speakers who actually succeeded in doing things right (thinking also outside of Cambridge). People likefor example Rik Henson from MRC-CBU - they have an institution-wide policy on Open Science. How did they achieve this? What were the drivers? 

Maybe someone that @corinalogan knows from Max Planck?

Maybe someone from [MNI](http://www.sciencemag.org/news/2016/01/montreal-institute-going-open-accel-erate-science) that @KirstieJane knows?

And perhaps then some of the doathon groups could work on designing effective strategies (together with an execution plan) to approach these different groups of stakeholders.

**Comment by lgatto** [comment]
I think OCC has to be a positive event. I can't see anything positive from discussions with local senior management: it's either no discussion, internal negotiations behind closed doors, or hostile attitude behind more closed doors. Any discussion should be with people that can make a change - interactions with middle management (whether from this institution, publishers, ...) is generally a waste of time. 

From my experience for the last 12 months or so, an effective strategy (possibly the only one) is to engage publicly, loudly and widely, hence my interest in @corinalogan suggestion. 

Hearing success stories from elsewhere is of course also welcome, of course.

**Comment by corinalogan** [comment]
@martateperek I'm happy to recommend people from MPI once a theme has been chosen. Will keep checking back to see what people decide...

**Comment by lgatto** [comment]
Here's a short summary of our discussion - present were Lucy from OSC, @KirstieJane, Naomi and @lgatto

### Meeting

There seems to be a consensus that we should be aiming for a theme centred around the involvement and contributions of individuals to make a change in the state of open science and open research. These contributions range from small and discrete to very vocal and involved, reflecting many flavours of supporting open means, and how much people are ready to invest; there is a place for everybody. 

One topic that we could run along this topic, focused on researchers and early career researchers in particular would be *how can open science be empowering*, or *how to stand out by being an open scientists*. Again, there is room for a wide range of openness.

We also thought that this year, we could try to be a bit more focused in the selection of speakers, a focus on the theme of what is the future of open, how can we influence it (what range of actions), and how can we make it work for use, as individuals.

An important goal was to make sure the event was of interest to seasoned open advocates, but also people that are less knowledgeable or involved, and show how they can benefit from and contribute to greater openness in their activities.

### Do-athon 

The second day would be focused on resources to promote open, to lower activation energy for change. For example, we could produce material addressing
- Simple answers to questions like: Why is it bad/dangerous to use Elsevier products
- What is modern scholar (digital) communication, and how traditional, commercial publisher limit progress
- A simple guide to Zotero for Mendeley users

### Next steps

- prepare a list of possible speakers that would be a good fit for the overall theme
- think of a good title for the meeting

**Comment by npscience** [comment]
Thanks Laurent, that's a great summary from my notes too. Only a couple of points to add:

>  These contributions range from small and discrete to very vocal and involved, reflecting many flavours of supporting open means, and how much people are ready to invest; there is a place for everybody.

The aim being for everyone to leave the room feeling like there is something (no matter how big or small) that they could do to improve their own life/career through the variety of options presented.

> One topic that we could run along this topic, focused on researchers and early career researchers in particular...

For two reasons:
* focussing attention may be more productive in achieving a result
* realistically, this is who we're likely to get in the room anyway

**Comment by rollerlibrarian** [comment]
I'm happy to assist with the Zotero themed segment for the Do-athon...just putting that out there.

**Comment by lgatto** [comment]
As part of this year's meeting, we want to emphasise that Open Science has many ways, and make sure that everybody feels welcome to contribute how they see fit. The following messages on twitter seemed particularly relevant in that respect:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">It was a damned hard community to break into. Any step I took to be more open, I felt attacked for not doing enough/doing it right.</p>&mdash; Christie Bahlai (@cbahlai) <a href="https://twitter.com/cbahlai/status/871413258107981824">June 4, 2017</a></blockquote>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Anyway- I believe in the open sci mission- that&#39;s why I&#39;m still here- but we need to really think about how we move forward.</p>&mdash; Christie Bahlai (@cbahlai) <a href="https://twitter.com/cbahlai/status/871415702376374274">June 4, 2017</a></blockquote>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">It&#39;s not just about choosing right licences and putting code on github, it&#39;s about actually improving accessibility and bringing people in</p>&mdash; Christie Bahlai (@cbahlai) <a href="https://twitter.com/cbahlai/status/871416201414574081">June 4, 2017</a></blockquote>

This is particularly relevant for under-represented minorities (URMs).

Food for thoughts for our coming meeting.

**Comment by cbahlai** [comment]
Oh, hi! Given that I work in this space a lot, please feel free to reach out if you want to chat about this at all!

**Comment by lgatto** [comment]
Thank you so much @cbahlai for following up! 

I would love to chat with you about making open science more inclusive, and how to make less exclusive with unwanted attitudes. What would be the best way to discuss - email, mailing list, github issue, ...? Do you have a blog post or another reference to get me/us started?

**Comment by cbahlai** [comment]
Here's a blog post where I touch on some of the issues: https://practicaldatamanagement.wordpress.com/2014/10/23/baby-steps-for-the-open-curious/

It's super old now, oy! And not to shamelessly self-promote, but I touch on many of these issues in my Open Science And Reproducible Research/ rebranded to Reproducible Quantitative Methods class (to reduce alienation of the uninitiated)- course material here:
https://cbahlai.github.io/rqm-template/

About 1/3 of the class time is devoted to navigating issues of open science in the current scientific paradigm- basically, we looked at how to be open and still survive as an academic scientist who is...erm...*not* incentivized to engage in open practice.

**Comment by cbahlai** [comment]
Oh, I forgot, just fire emails at will. my username at msu dot edu

**Comment by npscience** [comment]
@cbahlai thanks so much for joining the discussion here and for the resources.

@lgatto thanks for bringing this up for OCC. 

My tuppence: showing small ways people can move towards open science without compromising their other priorities, and whilst being radically inclusive, seems like an excellent mission for this year. I advocate that the final theme for OpenConCam reflects this.

**Comment by rollerlibrarian** [comment]
Following on from being radically inclusive, I think we also need to (at some point, whether this year or next) address issues of inclusiveness within open...how many people are in positions to be able to campaign or lead by example? This can fold into many intersectional areas relating to gender identity, race, privilege, being part of an institution etc. etc. While I am by no means an expert here, I would be fascinated to hear someone speak who is so I can learn.

**Comment by KirstieJane** [comment]
Hey thread!

How about _"Making Open Work for Everyone"_ as the theme for OpenConCam 2017.

Please emoji vote :+1:, :-1:

**Comment by KirstieJane** [comment]
Ok, I'm closing this issue - we have a theme! Yaaaay :tada:
