### ISSUE TITLE
OpenConCam 2017 Roadmap

### ISSUE THREAD

**Issue by KirstieJane** [OpenConCam/OpenConCam#13]
This is a list of issues that need to be completed in order to make our third annual OpenConCam event a success!

### High priority issues

* **Theme** - Check out #11 for discussions on what theme we should have this year
* **Dates and location** - Check out #14 for discussions on dates and location for this year's event
* **Do-Athon** - Check out #15 for discussions around running a "Do-Athon" (like a hackathon but with a broader definition of how to participate!) as part of OpenConCam 2017

### Next in line discussions

* **Speakers** - We need to figure out our themes before we think about who to invite as speakers, but if you have any suggestions you'd like to keep on record, please comment on #16 
* **Sponsorship levels** - It may be very sensible to define sponsorship levels and what sponsors can expect in exchange for their support, please comment on #17 
* **Budget** - If anyone has thoughts about costs for OpenConCam 2017 please comment on #18

**Comment by lgatto** [comment]
I'm closing this issue and replace it with a [project](https://github.com/OpenConCam/OpenConCam/projects/1), which is a bit easier to manage a set of related issues and overview their progress.
