### ISSUE TITLE
Dates & Location for OpenConCam 2017

### ISSUE THREAD

**Issue by KirstieJane** [OpenConCam/OpenConCam#14]
We've always had OpenConCam in November, and had reserved Thursday 23rd November for a one day workshop in the [Betty and Gordon Moore Library](http://moore.libraries.cam.ac.uk/).

Does that still work for everyone? ***Yvonne*** or ***Georgina*** is the room available?

* Update: room booked by @rollerlibrarian! Thank you Moore Library folk 🙌 

Could we have the "Do-Athon" (see issue #15) on the following day (Friday)? Or the Saturday? Or both Friday and Saturday to try to capture a broader range of people who may want to take part?

* Update2: As discussed in #15 @rollerlibrarian is not available for the do-athon on 24-25th Nov. Can we move OpenConCam to the week before: 16th-18th Nov?

* Update3: It looks we're converging on having a one day do-athon (see #15) and that 16th & 17th Nov work best for the majority.... any dissent?!

**Comment by corinalogan** [comment]
I'm not sure when I'll be around Sep-Dec because I will likely be in the field for part of that time, but I'll try to make it!

Do-Athon on the following day sounds great!

**Comment by yn235** [comment]
Of course! Yvonne

**Comment by rollerlibrarian** [comment]
Would you like me to reserve the room now so it's in the diary? I can do that very easily.

G

**Comment by KirstieJane** [comment]
Great stuff! Thank you @rollerlibrarian!!

**Comment by rollerlibrarian** [comment]
@KirstieJane Consider it moved!

**Comment by lgatto** [comment]
What are the new dates for the conference and do-athon?

**Comment by KirstieJane** [comment]
@lgatto see my update in the first post of this issue and the conversation at #15. Not set in stone yet though - still open for discussion.

**Comment by rollerlibrarian** [comment]
Looking at a convo on the Google group, looks like another event is taking place on 22nd in Tromso so yet another reason to shift dates so that event doesn't poach our lovely attendees...in the nicest possible way of course!

**Comment by lgatto** [comment]
I seems that we now have
- conference Thursday 23 November
- do-athon Friday 24 November
both at the Moore Library.

**Comment by rollerlibrarian** [comment]
Are these the dates? I thought we'd moved them back as I'm not around to help with the do-athon as well as the meeting in Tromso clashing...have I missed a new change?

**Comment by lgatto** [comment]
Oh sorry, I am confused then. Tromso is 22nd, so I thought these dates where the new ones, but obviously not. Sorry.

Everybody, could we try to set on dates rather earlier than late?

**Comment by rollerlibrarian** [comment]
Last I heard we were going for 16th for OCC and I assume the 17th for the do-athon. That is what is booked in and no one has asked me to change that...@KirstieJane?

**Comment by lgatto** [comment]
- If 16/17 November doesn't work for you, please mention it in a post.
- If 16/17 November does work for you, please add a thumbs up above.

**Comment by KirstieJane** [comment]
Sorry for being offline a bunch - I think 16/17 is the date we'd converged upon that works for most 😄
