### ISSUE TITLE
Do-athon as part of OpenConCam 2017

### ISSUE THREAD

**Issue by KirstieJane** [OpenConCam/OpenConCam#15]
For Open Data Day 2017 in March, @JosephMcArthur ran a Do-Athon in London: https://github.com/sparcopen/open-research-doathon.

The idea of a Do-Athon is a hackathon but with a much wider definition of participation than "hackathon" implies (not just code, lots of different actions count!).

@npscience had suggested that eLife might be interested in sponsoring an event like this, and it could possibly follow the workshop.

What do you think would be most successful for a Do-Athon? Is it worth organising?

**Update** to summarise some of the discussion below:
  * We'd like for the do-athon to be one day long and following the main OCC workshop
  * It's important to make clear to participants that they can come to either the workshop, or the do-athon, or both days. They won't be required to attend both!
  * By mid-June @JosephMcArthur will have worked on adding more documentation to the https://doathon.org website and [github repo](https://github.com/sparcopen/do-a-doathon), so we should have an excellent resource for our Do-Athon in November :smile:

**Comment by lgatto** [comment]
I am available.

**Comment by JosephMcArthur** [comment]
Thanks for the tag! Let me know if you'd like to do this, I want to write up a guide for doing these & a  willing alpha tester would help a lot (and in turn make your life easier).

**Comment by rollerlibrarian** [comment]
Sounds cool. If it is planned for the days just after OpenConCam then I won't be able to attend as I have a wedding to go to but am happy to help with the organisation.

**Comment by martateperek** [comment]
Hmmm.... @rollerlibrarian is quite a key person for OCC... Could we do this a week before or a week after so that @rollerlibrarian could be part of this? (both 16-18/11 and 30/11 -2/12 work for me and the OSC as it seems from looking into oour team calendars)

**Comment by rollerlibrarian** [comment]
I'm flattered @martateperek! Just to give you an idea of availability, I will definitely be away on 24th and 25th November. 16-18/11 works for me too as does 30/11-2/12.

**Comment by lgatto** [comment]
I'm fine with any these weeks.

**Comment by KirstieJane** [comment]
I can do 16-18 November but not 30/11 to 2/12.

@rollerlibrarian - would you mind checking to see if the glass room is available 16-18 Nov?

**Comment by rollerlibrarian** [comment]
@KirstieJane The Glass Room is free for those days and I've booked them out in the diary. 👍 Ideally if we could hold OCC and the partner event during the week then staffing would be much easier, as would access, for the whole building. Outside of weekdays we start getting in to swipe card access and other fiddly bits. Not impossible to manage, just something to consider as it would make our lives easier/harder depending on what we go for.

**Comment by rollerlibrarian** [comment]
@KirstieJane As a follow up question to my points about access over a weekend, is there a reason for us to be doing it after OCC? We could do it as a pre-event to lead up to the conference itself.

**Comment by lgatto** [comment]
Regarding event over the weekend, please be mindful that those will families will most likely not be available.

**Comment by KirstieJane** [comment]
@rollerlibrarian, @lgatto (et al) - I had thought that doing the do-athon over 2 days - one week day and one weekend day - might allow a larger range of people to attend at least one of the days. But I hadn't thought about access on the weekend so that might make the planning very different. Maybe just one day (Friday) would work.

Re: having it before OCC - I had also imagined that we could spend OCC discussing what needed to be done (around a particular theme) and then enacting some of those plans at the do-athon.

Very open for alternate plans/timelines though! What do you all think?

**Comment by lgatto** [comment]
My preference would for OCC, then do-athon for the same reason as you mention. The other way would also spit the participant community into those that did, and those that didn't. 

I would favour 2 days, 1 day conf and 1 day do-athon. Three days is more difficult to fit in for many, and hence the participants will be more fragmented between conference and/or do-athon.

**Comment by npscience** [comment]
I concur with the 2-day conference/doathon schedule. Inspire new people then invite them to act.

**Comment by rollerlibrarian** [comment]
I'm going to stick my oar in and also say a big YES to a two day event. Aside from the points already made about childcare and other commitments, I think 2 days is more manageable as well as less intimidating when trying to commit time or ask line managers for permission. Also we can keep our energy/excitement levels high for that period of time more easily ;)

**Comment by KirstieJane** [comment]
@lgatto @rollerlibrarian @lgatto - I feel like we've reached consensus - 2 day event - Thursday workshop, Friday do-athon. (I think I was the lone "3 dayer" person and I've been completely convinced that 2 days is better!)

Shall I close this issue? Does anyone else have any thoughts before I do?

**Comment by rollerlibrarian** [comment]
No more duration-related thoughts but I think when we start promoting the event we should give people the options to choose either OCC only or both days and promote them as intrinsically linked but also not as something people will be locked into attending if they can't make one or the other. Does that make sense?
 
Offer flexibility is I think what I'm trying to say.

**Comment by JosephMcArthur** [comment]
Before you shut, just wanted to jump in and say that before / during the mozilla global sprint Daniel Mietchen & I will finish our documentation of the doathon concept. 

We've got a site coming into being here https://doathon.org/, but the repo (linked from the site) is where the meat is at the moment. 

We'd LOVE feedback, requirements etc as we build.

**Comment by KirstieJane** [comment]
@JosephMcArthur - BRILLIANT! Thank you! We'll definitely keep an eye out for the repo development!

@rollerlibrarian - that's a great point! I'll add it to the notes at the top.

I didn't mean to cause any panic on the issue closing, I just thought we could start a clean one now we know we agree that a do-athon is a good idea :smile:

Happy to keep this open for more discussion though!

**Comment by lgatto** [comment]
Based on a [discussion about the theme of the conference](https://github.com/OpenConCam/OpenConCam/issues/11#issuecomment-303514279), it seems that centres around *theme centred around the involvement and contributions of individuals to make a change in the state of open science and open research*.

As for the do-athon, it could be focused on resources to promote open, to lower activation energy for change. For example, we could produce material addressing
- Simple answers to questions like: Why is it bad/dangerous to use Elsevier products
- What is modern scholar (digital) communication, and how traditional, commercial publisher limit progress
- A simple guide to Zotero for Mendeley users
- A short document describing how to add an (existing) addendum to retain copyright of ones work, and explain that this then gives the right to redistribute the content (not publisher's layout).

**Comment by lgatto** [comment]
Given the lack of time of the organisers, it was decided to drop the do-athon.

**Comment by rollerlibrarian** [comment]
So does this mean the Glass Room booking for the Friday can now be cancelled? It was the Friday wasn't it?

**Comment by lgatto** [comment]
Yes, indeed, sorry for this. It is a bit of a shame :-/

**Comment by rollerlibrarian** [comment]
These things happen. Good to know about the booking as I can now cancel it :)
