### ISSUE TITLE
Sponsorship levels

### ISSUE THREAD

**Issue by KirstieJane** [OpenConCam/OpenConCam#17]
Last year we were incredibly successful at raising funds (THANK YOU to our amazing sponsors 🎉 ✨!)

One of the things we didn't do, but I think we realised it would have been sensible, is to define some different levels of support and be very clear what the sponsors can expect in exchange for their money.

Here are two resources from OpenCon that are important for this conversation:

* http://www.opencon2017.org/sponsorship_guidelines
* http://www.opencon2017.org/funding_a_satellite_event

**Comment by corinalogan** [comment]
Do we have any money leftover from last year? How much are we expecting this OCC to cost?

**Comment by KirstieJane** [comment]
@corinalogan - great question. I think this is a slightly different discussion to setting sponsorship levels so I've made a buget issue: #18

**Comment by lc340** [comment]
I think it would be really nice if we could use some of the sponsorship money to provide childcare for attendees this year. It would help open up attendance to working parents. That's assuming we are successful in getting sponsorship again!

**Comment by npscience** [comment]
Specific Q: how much will hosting the doathon cost?

Venue - is the use of the glass room free @rollerlibrarian ?
Food - I'm guessing this is the major expense. How many would we aim to cater for?
Any other costs? I note @lc340 suggested childcare provisions in another thread.

cc @KirstieJane

**Comment by rollerlibrarian** [comment]
Yes @npscience the Glass Room use is completely free but you're right to flag up food which can be pricey.

**Comment by KirstieJane** [comment]
Thanks @npscience!

I think the room is free, and we'd be looking for around £20/person for the food (morning and afternoon coffee, lunch and wine).

I'm not sure how many people would come to the do-athon but what about budgeting for 40 people? So £800 for the do-athon day?

What do others think? Does that make sense?

The workshop we had 80 people budgeted for last year, so more like £1600 for the Thursday...

**Comment by KirstieJane** [comment]
Gah - forgot to budget in childcare. I asked a friend and she suggested £100/5 hours. So maybe £200 for the day. That's for one person so it clearly depends on how many children they can look after.

I'm not sure how many people will need childcare at OpenConCam. What do you all think the number of people who would need it would be? Maybe planning for 2 childcare professionals which would be approx 8 children? 

£800 maximum

**Comment by rollerlibrarian** [comment]
Possibly silly question but would the childcare happen on site? If so we have our study rooms that can be booked as a space for sproglets.

**Comment by KirstieJane** [comment]
Not silly @rollerlibrarian at all. I don't know, but I think I had assumed so. If there's a room available that would be great!

**Comment by rollerlibrarian** [comment]
I can book them both and maybe we can check their suitability nearer the time @kirstiejane?

**Comment by KirstieJane** [comment]
Awesome :tada: Thank you @rollerlibrarian!

**Comment by lgatto** [comment]
Some comments about child care 
- child care would only be useful to those with young children children or toddlers, who don't go to school or nursery
- for those that have children that go to school/nursery, child care won't be helpful at all, as they will have to leave at, say 3pm (in pre- and primary school), to pick the children up, and are unlikely to come back
- the meeting pretty much overlaps with a work day, so it is very likely that child care arrangements are made anyway

What I, as a parent, would find most useful, is a meeting that starts and ends at times compatible with schools times, i.e. something like 9.30am to 3pm, or at least if the meeting goes until 4pm, it's not like the most important part that I would miss if I have to leave by 3pm. Of course, this only applies to those locals, but that is our main target audience. I think it would be a different story for carers that travel to Cambridge.

So before committing to child care, I think it would be worth asking people when they register, or send a survey out to those that attended previously.

**Comment by lc340** [comment]
My idea about childcare was for people coming from far away who can't access their regular childcare that day. In my case, nursery opens at 8am so I can't make events further away than London. Plus I'm usually late and have to leave early in order to pick the little one up in time. Childcare on site might allow someone to come from futher afield and attend all day. 

I think surveying people on registration/before is a good idea. It would also help plan with costs/staff because there are legal restrictions on the adult/child ratio depending on the ages of the children.

**Comment by lgatto** [comment]
Are there also plans to organise childcare on the day preceding OpenConCam for the OSC event, which will gather a much more international crowd.

**Comment by lc340** [comment]
Yes. I believe we're going to ask on registration if anyone is interested in this.

**Comment by rollerlibrarian** [comment]
Is this a new approach @lc340 as I don't think I've ever seen any other uni event offer such a thing. But then I don't have kids so I might just have missed that bit.

**Comment by lc340** [comment]
Yes it is a new approach and not many events offer it. I've just now got my "I'm a working mother" soapbox to stand on and I feel the need to champion making things accessible to working mothers (and fathers of course). I feel a rant coming on so I'll stop there.

**Comment by rollerlibrarian** [comment]
I thoroughly approve. Equality for all and access for all is critical. More of this please.

**Comment by lgatto** [comment]
Two weeks ago, I was at a relatively large international conference (1000 delegates) in Brussels, and they had childcare arrangements throughout the week (which they charged for, however).

**Comment by lc340** [comment]
Hi all, can you remind me which sponsors we are intending to target first? We spoke about this two meetings ago and we agreed that as we didn't need much money we'd approach a couple of sponsors (PLOS? eLife?) and see if that raises enough. I'm just working on sponsorship stuff for the Data Champions event that is running the day before and it would be handy to have this info. Thanks.

**Comment by KirstieJane** [comment]
@lc340 - I'm not 100% sure we did decide who we were going to target first. Would you mind sending an email to the openconcamcommittee list? I think that's going to be the best place for discussions on this point...
