### ISSUE TITLE
Budget

### ISSUE THREAD

**Issue by KirstieJane** [OpenConCam/OpenConCam#18]
What do we expect our outgoings to be for OpenConCam 2017?

(Note that of course this will be dependent on what we decide for the do-athon #15, and who we invite as speakers #16...but at least we can start the conversation here!)

How much do we have left over in our bank account from last year?

### Budget estimate

* Glass room at Moore Library on Thursday & Friday: free
* Morning & afternoon coffee, lunch and wine for 80 people on Thursday and 30 people on Friday: 80\*20 + 30\*20 = £2200
* Swag: pens left over from last year

**Comment by npscience** [comment]
Are we paying any of the speakers? Particularly is some are coming to 'give' us a different perspective, but with little 'take' for them?

Also, if any speakers are non-Cambridge, then travel expenses? I guess this will be easier to estimate once we have finalised the list of speakers to invite. (Could we do Hangouts for non-Cambridge speakers to minimise the cost to them, unless they value the networking opportunity?)

**Comment by KirstieJane** [comment]
@npscience - I don't think we have the budget to pay speakers an honorarium, but I do think we should try to cover travel costs where necessary. If we feature local speakers they won't need funds and I agree that hangouts for one non-Cambridge speaker makes sense.

**Comment by corinalogan** [comment]
I don't think we will need to buy more swag this year because I think there was lots leftover from last year (pens! :) ). Who took the box(es) of swag to their office?

I think @jcmolloy has the budget from last year and knows how much money is leftover.

**Comment by rollerlibrarian** [comment]
We had two boxes left in the library so a lot of stuff was recycled like sponsor leaflets but we still have boxes of pens which we've been giving out to users as and when as we weren't sure if they were still wanted or not as no-one came to collect them after last year. We also posted CUP's table cloth back to them as I know they're quite pricey.

**Comment by jcmolloy** [comment]
There is £1050 left from last year - happy to transfer this to whoever is happy to organise the finances this year. I can help but if we could share the admin load to a different department that would be great so Plant Sciences accounts aren't doing all the invoicing again. If we go with the plan of sticking to just a few key sponsors then it won't be as much this year anyhow.
