### ISSUE TITLE
Profile update: Keren Limor-Waisberg

### ISSUE THREAD

**Issue by KerenLW** [OpenConCam/OpenConCam#2]
Name:  Keren
Surname:  Limor-Waisberg
Short profile:  Enabling scientific literacy and promote a more accessible, inclusive, and collaborative science.
Open tags:  
www:  Literacytool.com
email:  keren@literacytool.com
twitter:  @TheLiteracyTool
GitHub:  @KerenLW
facebook:  facebook.com/theliteracytool
keybase:  
google+:  
linkedin:  uk.linkedin.com/in/kerenlimorwaisberg
(add other social media)

**Comment by lgatto** [comment]
Thanks @KerenLW - could you add a couple of *open tags* highlighting your interests.

**Comment by KerenLW** [comment]
Sure:
I'll go with Marta's Open Mind!  Then - open research, open access, and open science

**Comment by lgatto** [comment]
Thanks, alls updated now. Closing issue.
