### ISSUE TITLE
Update website with save the date information

### ISSUE THREAD

**Issue by KirstieJane** [OpenConCam/OpenConCam#20]
I wonder if anyone has time (@Bjwebb, @lgatto maybe??) to update the [OpenConCam website](http://www.openconcam.org/) with save the date information about OpenConCam2017?

Here's the repo: https://github.com/OpenConCam/OpenConCam.github.io

Here's some text that Lucy wrote for us, and that went out in the OSC Research Data Management Newsletter:

> SAVE THE DATE: OpenCon Cambridge 2017
>
> 16-17 November
> University of Cambridge
>
> [OpenCon 2017](http://www.opencon2017.org/) is the student and early career academic professional conference on Open Access, Open Education and Open Data, this year being held from 11-13 November in Berlin, Germany. OpenCon Cambridge is a satellite event that will bring together students, early career academic researchers and open advocates from around Cambridge and beyond! The theme of this year is Making Open Work for Everyone with the first day focusing on a series of talks and discussions, and for the first time ever a second day taking the format of a Do-athon.

**Comment by Bjwebb** [comment]
I've made a pull request with the change - https://github.com/OpenConCam/OpenConCam.github.io/pull/12 - but I don't have the permissions to actually merge and deploy it.
