### ISSUE TITLE
List of lunches

### ISSUE THREAD

**Issue by jcmolloy** [OpenConCam/OpenConCam#8]
Wondering if we should list upcoming lunches and how to find us on the site, now they are fairly regular and we plan to use the postdoc centre?

**Comment by lgatto** [comment]
I have update the page:

> We meet every first Wednesday of the month over lunch. Get in touch if you want to join.

We had plans to to try another venue, so I didn't mention the University Centre.

**Comment by lgatto** [comment]
Anything else?

**Comment by lgatto** [comment]
Sorry, I missed the PR - merging now.

**Comment by jcmolloy** [comment]
Thanks! I had the same thought process as you, should have closed the issue
myself ;)
