### ISSUE TITLE
Committee email list

### ISSUE THREAD

**Issue by KirstieJane** [OpenConCam/OpenConCam#9]
I'm happy that we've organised the speakers and the themes etc of the conference on the OpenConCam mailing list....but now that we're getting closer to our event I think it would be wise to set up a different OpenConCam2016Committee list so we're not spamming everyone.

@lgatto - did you make the list? Would you mind making another?

Thank you!

**Comment by lgatto** [comment]
@KirstieJane - would you like a google group, or a private gitub repository (we would use issues to discuss specific points and refer to files we need for the organisation). The problem I see with github is that I'm not sure everybody on the committee has a github account.

**Comment by KirstieJane** [comment]
Thanks @lgatto. A google group was what I'm thinking. I agree that GitHub is great....but not for everyone on the organising team.

**Comment by KirstieJane** [comment]
I don't think it needs to be private by the way. Just a way to separate the planning from the main mailing list!

**Comment by lgatto** [comment]
> I don't think it needs to be private by the way

Sorry, I misunderstood you. Will create an OpenConCamCommittee list (that we can recycle over the years) and announce it on the main mailing list.

**Comment by KirstieJane** [comment]
Amazing! Thank you!

**Comment by lgatto** [comment]
Done
